## One-Dimensional Array

In [3]:
import numpy as np
x = np.array(['A','B','C'])
print(x)

['A' 'B' 'C']


## More than one dimensional array

In [4]:
x = np.array([['A','B','C'], ['D','E','F']])
print(x)

[['A' 'B' 'C']
 ['D' 'E' 'F']]


## "shape" Attribute

In [5]:
x = np.array([['A','B','C'], ['D','E','F']])
print(x)
print(x.shape)

[['A' 'B' 'C']
 ['D' 'E' 'F']]
(2, 3)


In [45]:
x = np.array([['A','B','C'], ['D','E','F']])
x.shape = (3, 2)
print(x)

[['A' 'B']
 ['C' 'D']
 ['E' 'F']]


## "reshape" Attribute

In [18]:
import numpy as np
x = np.arange(25)

print(x)

z = x.reshape(5,5)    # x.reshape(row, column, shape)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
import numpy as np
y = np.arange(8)
z1 = y.reshape(2,2,2)  # x.reshape(row, column, shape)
print(z1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## "itemsize" Attribute

In [26]:
# itemsize = "size in byte"

x = np.array([1, 2, 3], dtype = np.int8)
print('int8 = ',x.itemsize)

x = np.array([1, 2, 3], dtype = np.int)
print('int = ',x.itemsize)

x = np.array([1, 2, 3], dtype = np.float)
print('float = ',x.itemsize)

x = np.array(['1', '2', '3'], dtype = np.str)
print('str = ',x.itemsize)

int8 =  1
int =  4
float =  8
str =  4


## "asarray" Attribute

In [30]:
# Using List

import numpy as np

l = [1, 2, 3]
print(l)
x = np.asarray(l)
print(x)
y = np.asarray(l, dtype=float)
print(y)

[1, 2, 3]
[1 2 3]
[1. 2. 3.]


In [31]:
# Using Tuple

l = (1, 2, 3)
x = np.asarray(l)
print(x)

[1 2 3]


## "arange" Attribute

In [33]:
x = np.arange(10, 20, 2, float)    # arange(start, end, skip, dtype)
print(x)

[10. 12. 14. 16. 18.]


## "linspace" Attribute

In [38]:
# linspace(start, end, skip, endpoint, retstep, dtype)
# suppose: end=20 and endpoint=20 : 20 will be included after 19

x = np.linspace(1, 2, 5, retstep=True)
print(x)

y = np.linspace(1, 2, 5, retstep=True, endpoint=False)
print(y)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
(array([1. , 1.2, 1.4, 1.6, 1.8]), 0.2)


## "logspace" Attribute

In [43]:
# numpy.logspace(start, end, skip, endpoint, base, dtype)

x = np.logspace(1, 10, 10, base = 10)
print(x)

x = np.logspace(1, 10, 10, base = 2)
print(x)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


## Indexing

In [47]:
x = np.random.randint(10, size=6)
print(x)

[6 9 7 5 0 6]


In [48]:
x1 = np.random.randint(10, size=(4,3))
print(x1)

[[5 9 2]
 [7 4 8]
 [9 8 2]
 [6 9 8]]


In [54]:
# One dimensional Array

print(x[2])

7


In [53]:
# More than one-dimensional Array

print(x1[2,2])

2


## Slicing

In [56]:
# One dimensional Array

print(x[2:])
print(x[:-1])

[7 5 0 6]
[6 9 7 5 0]


In [68]:
# More than one dimensional Array

print(x1[:2,:3])  # two rows & three columns
print()
print(x1[:2,:2])
print()

print(x1[1:,1:])
print()
print(x1[1:,1:2])

[[5 9 2]
 [7 4 8]]

[[5 9]
 [7 4]]

[[4 8]
 [8 2]
 [9 8]]

[[4]
 [8]
 [9]]


## Aggregate Calculation

In [73]:
# sum, max, min, average, variance

print(x)

y = np.sum(x)
print('sum = ',y)

y = np.min(x)
print('min = ',y)

y = np.max(x)
print('max = ',y)

y = np.mean(x)
print('average = ',y)

[6 9 7 5 0 6]
sum =  33
min =  0
max =  9
average =  5.5


## Sorting

In [77]:
print(x)

srt = np.sort(x)
print(srt)
srt1 = np.argsort(x) # index of sorting elements in non-sorting dtype
print(srt1)

[6 9 7 5 0 6]
[0 5 6 6 7 9]
[4 3 0 5 2 1]


In [80]:
# Sorting along rows

print(x1)
print()
print(np.sort(x1, axis = 0))

[[5 9 2]
 [7 4 8]
 [9 8 2]
 [6 9 8]]

[[5 4 2]
 [6 8 2]
 [7 9 8]
 [9 9 8]]


In [81]:
# Sorting along column

print(x1)
print()
print(np.sort(x1, axis = 1))

[[5 9 2]
 [7 4 8]
 [9 8 2]
 [6 9 8]]

[[2 5 9]
 [4 7 8]
 [2 8 9]
 [6 8 9]]


## Partitioning

In [89]:
print(x)

print(np.partition(x,2)) # only sort 2 values

[6 9 7 5 0 6]
[0 5 6 9 7 6]
